version: '3.8'

services:
  web:
    build: ./
    command: python manage.py run -h 0.0.0.0
    ports:
      - "5001:5000"
    env_file:
      - ./.env.dev

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
volumes:
  postgres_data: